# Identificador único (puedes poner lo que quieras, pero sin espacios)
sonar.projectKey=calidadmetricas-ishelperapp

sonar.sources=lib
sonar.tests=test

sonar.language=dart
sonar.sourceEncoding=UTF-8

sonar.dart.linter.reportPaths=flutter_analyze_report.txt

sonar.flutter.coverage.reportPath=coverage/lcov.info
